### ISSUE TITLE
`karmor install --local` does not set `ImagePullPolicy` to `IfNotPresent` for all containers

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubearmor/kubearmor-client#307]
### Description
`--local` flag does not set `ImagePullPolicy` to `IfNotPresent` for many containers across different deployments. For example:
```yaml
    spec:
      containers:
      - image: kubearmor/kubearmor-relay-server:latest
        imagePullPolicy: Always # This should have been IfNotPresent
        name: kubearmor-relay-server
```
### Work in the scope of this issue
Check all pod controllers (deployments, daemon sets, etc.) deployed by `karmor install` have `ImagePullPolicy` set to `IfNotPresent` for all containers if `--local` flag is specified.
