### ISSUE TITLE
feat : Karmor support for non k8s installation

### ISSUE THREAD

**Issue by Aryan-sharma11** [kubearmor/kubearmor-client#484]
Karmor client should able to install kubearmor in non kubernetes environment (docker/systemd).

Deliverables: 
1.  As a docker  container: 
     -  docker compose should be configurable( visibility, default posture etc) and embedded in cli tool itself. we can make use of golang embed library for this.
     - karmor uninstall should work  
2. As a systemd service
    -  Kubearmor tar can be downloaded via github releases or from docker [registeries](https://hub.docker.com/r/kubearmor/kubearmor-systemd/tags).
    -  Kubearmorconfig.yaml  should be configurable here too, the config file will also be embedded along with the tool itself.
    -  Karmor uninstall should work.

**Comment by itsCheithanya** [comment]
>    * Kubearmorconfig.yaml  should be configurable here too, the config file will also be embedded along with the tool itself.

@Aryan-sharma11 can you elaborate
this and how do you wish to do this?

**Comment by Aryan-sharma11** [comment]
> > * Kubearmorconfig.yaml  should be configurable here too, the config file will also be embedded along with the tool itself.
> 
> [@Aryan-sharma11](https://github.com/Aryan-sharma11) can you elaborate on this?

Sure @itsCheithanya, by configurable, I mean that a template configuration file should be present, and fields like visibility and maxalertpersec should be dynamically populated from the CLI.
for ref [templates](https://pkg.go.dev/text/template) , [embed](https://pkg.go.dev/embed)

**Comment by Aryan-sharma11** [comment]
> > > * Kubearmorconfig.yaml  should be configurable here too, the config file will also be embedded along with the tool itself.
> > 
> > 
> > [@Aryan-sharma11](https://github.com/Aryan-sharma11) can you elaborate on this?
> 
> Sure [@itsCheithanya](https://github.com/itsCheithanya), by configurable, I mean that a template configuration file should be present, and fields like `visibility` and `maxalertpersec` should be dynamically populated from the CLI. for ref [templates](https://pkg.go.dev/text/template) , [embed](https://pkg.go.dev/embed)

for example the config file should be like 
```yaml
cluster: "default"
gRPC: "32767"
visibility: {{.KubeArmorVisibility}}
hostVisibility: {{.KubeArmorHostVisibility}}
enableKubeArmorHostPolicy: true
enableKubeArmorVm: false
k8s: false
alertThrottling: true
maxAlertPerSec: {{.KubeArmorMaxAlertsPerSec}}
throttleSec: {{.KubeArmorThrottleSec}}
```
