### ISSUE TITLE
kubearmor policy simulator

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/kubearmor-client#79]
## What is the problem statement and use-case for this?
Kubearmor supports policy enforcement and this enforcement is guided by two factors:
1. The policy itself
2. Kubearmor configuration (such as `defaultPosture`, `auditOnlyMode` etc)

It is possible to put up a document to explain all the combination as in, if X is the policy and Y is the configuration and if we get an action exec/fopen/network-connect etc, how will the policy react? However, using a document for such purpose seems non-efficient. Also it can very easily get complicated since every configuration has multiple values (for e.g. `defaultPosture` could be Audit/Block/Allow). As an example, check the discussion on [this PR](https://github.com/kubearmor/KubeArmor/pull/727). It  is better if we can simulate the event/action-result given the inputs. Later on, we can have a web-page hosted that can depict this in a more user friendly way.

## Example cli
```
karmor simulate --config kubearmor.cfg --policy policy.yaml --action "exec:/bin/sleep"
karmor simulate --config kubearmor.cfg --policy policy.yaml --action "exec:/bin/bash->/bin/sleep" ... specifying ls spawned as a child process of bash
```
<details>
  <summary>Sample policy.yaml</summary>
  
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-group-1-proc-path-block
  namespace: multiubuntu
spec:
  selector:
    matchLabels:
      group: group-1
  process:
    matchPaths:
    - path: /bin/sleep
  action:
    Block
```
</details>

### Sample run
Assuming the command used is:
```
karmor simulate --config kubearmor.cfg --policy policy.yaml --action "exec:/bin/sleep"
```

Expected Output:
```
Action: Block

Telemetry Event:
== Alert ==
Cluster Name: unknown
Host Name: unknown
Namespace Name: unknown
Pod Name: unknown
Container ID: unknown
Container Name: unknown
Labels: unknown
Policy: policy.yaml
Severity: 1
Type: MatchedPolicy
Source: /bin/sleep
Operation: Process
Resource: /bin/sleep
Data: syscall=SYS_EXECVE
Action: Block
Result: Permission denied
```

## Requirements:
- [ ] support multiple policies
- [ ] support configuration file for specifying kubearmor cfg
- [ ] support process based rules
- [ ] file based rules
- [ ] network based rules
- [ ] show the output action
- [ ] show the telemetry event that would be generated
- [ ] possible to specify multiple actions
- [ ] Support atleast following actions
    - [ ] process action: exec
    - [ ] file action: fopen
    - [ ] network action: socket, connect, accept

CC: @nam-jaehyun (was his idea)
